version: '3.1'
services:
  db:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: FA-db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - FA-db-data:/var/lib/mysql
volumes:
  FA-db-data: